name: Continues integration with nodejs

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm build
